# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Filecoin Improvement Proposals
description: >-
  Proposals to improve the Filecoin blockchain
url: "https://fips.filecoin.io"
# url: https://fips.filecoin.org // Suggested permanent URI

github:
  repository_url: "https://github.com/filecoin-project/FIPs"

# Build settings
highlighter: rouge
markdown: kramdown
theme: jekyll-theme-basically-basic
kramdown:
  parse_block_html: false
  # This is the default, but be explicit as some EIPs depend on it
  auto_ids: true
  # This is to ensure more determistic behaviour
  auto_id_stripping: true
  syntax_highlighter: rouge

permalink: /:path/:basename.html

defaults:
  -
    scope:
      path: "FIPS"
    values:
      layout: "fip"
      permalink: /:path/:basename.html

exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - templates/
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - README.md
